[package]
name = "ai_response_verifier"
type = "bin"
authors = ["Privacy Trading Team"]
compiler_version = ">=1.0.0"

[dependencies]
poseidon = { tag = "v0.2.0", git = "https://github.com/noir-lang/poseidon" }
